version: '3'
services:
  app:
    image: user/repository:tag
    ports:
      - '80:3000'
    networks:
      - web_net
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - web_net

networks: 
  web_net: